
###
POST http://localhost:8080/api/server
Cache-Control: no-cache
Content-Type: application/json

{
  "port": "8082",
  "static_resource": "./ui/web2"
}

### with token
POST http://localhost:8080/api/server
Cache-Control: no-cache
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE2MTM1NjE0ODUsInVzZXJfaWQiOjEzfQ.qX1Mn2Z9BumX8eNMFDbnOfOtKVjZ8MmlIgOCcMEAU9w

{
  "port": "8082",
  "static_resource": "./ui/web2"
}

###
GET http://localhost:8080/api/server
Cache-Control: no-cache
Content-Type: application/json

###
DELETE http://localhost:8080/api/server/1613455303
Cache-Control: no-cache
Content-Type: application/json

###
POST http://localhost:8080/api/auth
Content-Type: application/json

{
  "email": "2@2.ru",
  "password": "2"
}

###
GET http://localhost:8082/api/slave/server
Cache-Control: no-cache
Content-Type: application/json


###
GET http://localhost:8080/api/server
Cache-Control: no-cache
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE2MTM1NjE0ODUsInVzZXJfaWQiOjEzfQ.qX1Mn2Z9BumX8eNMFDbnOfOtKVjZ8MmlIgOCcMEAU9w
