
###
POST http://localhost:8080/api/server
Cache-Control: no-cache
Content-Type: application/json

{
  "port": "8082",
  "static_resource": "./ui/web2"
}

### with token
POST http://localhost:8080/api/server
Cache-Control: no-cache
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE2MTQ2MDM1NTUsInVzZXJfaWQiOjV9.quRrBeidEd_4_zP0rryjqUf06HfQtvkNyCihfRCxpmY

{
  "port": "8082",
  "static_resource": "./ui/web2"
}

###
GET http://localhost:8080/api/server
Cache-Control: no-cache
Content-Type: application/json

###
DELETE http://localhost:8080/api/server/1614603334
Cache-Control: no-cache
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE2MTQ2MDM1NTUsInVzZXJfaWQiOjV9.quRrBeidEd_4_zP0rryjqUf06HfQtvkNyCihfRCxpmY

### LOGIN
POST http://localhost:8080/api/auth
Content-Type: application/json

{
  "email": "12",
  "password": "12"
}

### LOGOUT
GET http://localhost:8080/api/logout
Content-Type: application/json

{
  "access_token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOjI0LCJhdXRob3JpemVkIjp0cnVlLCJleHBUb2tlbiI6MTYxNzE5Mjg0MX0.sus6zWZ7fajD2if3XMrptaSWSjE9_skFpI9GlrGCSsI"
}

### RefreshToken
POST http://localhost:8080/api/auth/refreshtoken
Content-Type: application/json

{
  "refresh_token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOjI0LCJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE2MTc4Njg1NjJ9.YuZ6NMIb03dg7dqETd9_lLPf0sa1RfS5_QBoOs1da2I"
}

###novalid registre
POST http://localhost:8080/api/user
Content-Type: application/json

{
  "email": "2@2.ru",
  "password": "2"
}
###VALID
POST http://localhost:8080/api/user
Content-Type: application/json

{
  "name":"12",
  "email": "12",
  "password": "12"
}

###
GET http://localhost:8082/api/slave/server
Cache-Control: no-cache
Content-Type: application/json


### get server VALID
GET http://localhost:8080/api/server
Cache-Control: no-cache
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOjI0LCJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE2MTczNDQ5MDd9.vFWjESeGtyvPBzkXZX-8De-JqlKteEpE1lb32A4GYkY

### get server UNVALID
GET http://localhost:8080/api/server
Cache-Control: no-cache
Content-Type: application/json


### test conect bd
GET http://localhost:8080/api/connect
Cache-Control: no-cache
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE2MTM2MzcxNzgsInVzZXJfaWQiOjV9.v5xpFOakFBAzKxm-f3BngHppJkrlKBGMrWf0XVW0_x4
### Panic
GET http://localhost:8080/api/panic
Cache-Control: no-cache
Content-Type: application/json
